title: Prakash Dura
logo: /assets/img/headshot_circle.jpg
description: text below image
show_downloads: true
theme: Jekyll-theme-minimal
# Social media links
social:
  - name: "GitHub"
    url: "https://github.com/PrakashDura"
    icon: "fab fa-github"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/prakashdura/"
    icon: "fab fa-linkedin"



