title: Prakash Dura
logo: 
  path: /assets/img/headshot_circle.jpg
  style: "border-radius: 50%; width: 150px; height: 150px; object-fit: cover;"
#description: text below image
show_downloads: true
theme: Jekyll-theme-minimal
# Social media links




