title: Prakash Dura
logo: /assets/img/headshot_circle.jpg
description: "<img src='/assets/img/headshot_circle.jpg' alt='Prakash Dura' style='border-radius: 50%; width: 150px; height: 150px; object-fit: cover;'> text below image
show_downloads: true
theme: Jekyll-theme-minimal
